name: "build the app and release the app"
on: 
    push:
        branches:
            - main
        
jobs:
    build:
        name: Build and Release job
        runs-on: macos-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: setup java
              uses: actions/setup-java@v3.12.0
              with:
                distribution: 'oracle'
                java-version: '17'
            
            - name: setup flutter
              uses: subosito/flutter-action@v2
              with: 
                flutter-version: '3.10.0'
                channel: 'stable'
                
            - name: install dependancy
              run: flutter pub get   
              
            #   skip test
            # - name: Install system image
            #   run: sdkmanager "system-images;android-30;default;x86"

            # - name: Start emulator
            #   uses: reactivecircus/android-emulator-runner@v2
            #   with:
            #     api-level: 30 # Specify the Android API level
            #     arch: x86 # Specify the emulator architecture
            #     profile: Nexus 5 # Specify the emulator profile
            #     startup-timeout-minutes: 5
            #     script: |
            #      echo "Emulator started successfully"
            # - name: Wait for emulator to start
            #   run: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'    
      
            - name: build my apk
              run: flutter run --release -d chrome
            
            - name: build my aab
              run: flutter build appbundle
            
            - name: build my IPA
              run: |
                cd build
                tar -czf ios_build.tar.gz ios
            
            - name: upload all my artifacts
              uses: actions/upload-artifact@v2
              with:
                name: all the releases
                path: |
                    build/app/outputs/flutter-apk/app-release.apk
                    build/app/outputs/bundle/release/app-release.aab
                    build/ios_build.tar.gz
            
            - name: create my releases
              uses: ncipollo/release-action@v1
              with:
                artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/app/outputs/bundle/release/app-release.aab,build/ios_build.tar.gz"          
                tag: v2.0.${{github.run_number}}
                token: ${{secrets.GITHUB_TOKEN}}
                    
